README.md, src/main/resources/schema/ans/v0_2/story.json, src/test/resources/com/washingtonpost/arc/ans/v0_2/model/story-fixture-good.json
I think the problem I was encountering previously was that the validator
was pulling down old schemas from github instead of the schemas on my
local filesystem.
This makes for some interesting (shitty) development environments
because it means you often have to commit schema changes you're not sure
work until you commit them....  seems like we need some branching
workflow to improve this, but it would mean changing the URLs in all the
schemas...
=> Adding promo_image and promo_images

README.md, RELEASE_NOTES.md, pom.xml, src/main/java/com/washingtonpost/arc/ans/v0_3/model/ANS.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Content.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Gallery.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Image.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Media.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Story.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Text.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Video.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/VideoStream.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/AbstractANSTest.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestStory.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestVideo.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestVideoStream.java, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/video-fixture-good.json, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/video-fixture-nationals.json, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/video-stream-fixture-good.json
* Moving the type declaration string down to each concrete child of the ANS parent
* Renaming Video.type to Video.videoType
* Renaming VideoStream.type to VideoStream.streamType
=> Configuring Jackson to re-use existing "type" field

src/main/java/com/washingtonpost/arc/ans/v0_3/model/ANS.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/RawHTML.java, src/main/resources/schema/ans/v0_3/raw_html.json, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestRawHTML.java, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/raw-html-fixture-bad.json, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/raw-html-fixture-good.json
The vast majority of failure cases in content ingestor at this moment are "transformer-error", which makes it difficult to test for and eliminate ingestion failure cases, as well as prevents content from being ingested. To that end, getting the raw_html element in place as a fallback will probably unblock us in the medium-run
=> Adds RawHTML schema type

RELEASE_NOTES.md, src/main/java/com/washingtonpost/arc/ans/ANSVersion.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Image.java, src/test/java/com/washingtonpost/arc/ans/TestANSVersion.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestImage.java, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/image-fixture-good-no-height-width.json
If we used Java "int"s for those fields then they'll show up as zeros
downstream if they are unset in the input JSON.
=> Making the Image.height & Image.width Integer to avoid "false zeros"

RELEASE_NOTES.md, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Collection.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Content.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/TraitDated.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/AbstractTest.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestImage.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestMedia.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestStory.java, src/test/resources/com/washingtonpost/arc/ans/v0_3/model/story-fixture-tiny-house.json
This corrects that and makes the native Date treatment of ANS TraitDated
objects use an RFC-3339 format String for representing Dates.
=> The spec/examples have been using Date RFC3339 formats, but the code was not

src/main/java/com/washingtonpost/arc/ans/v0_3/model/Collection.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/Content.java, src/main/java/com/washingtonpost/arc/ans/v0_3/model/TraitDated.java, src/test/java/com/washingtonpost/arc/ans/v0_3/TestANSTimeHandling.java
The SimpleDateFormatter I was using in the last commit wasn't
sufficiently nimble for the different types of timestamps we're seeing
in "real" Stories.  Instead of using jodatime with its IsoDateFormatter,
I think the latest Java 8 java.time package code should be able to
support our DateFormat requirements with the Instant class.
=> Replacing old Java date handling with newer java.time code

RELEASE_NOTES.md, src/main/java/com/washingtonpost/arc/ans/v0_3/model/StorySummary.java, src/main/resources/schema/ans/v0_3/story-summary.json, src/test/java/com/washingtonpost/arc/ans/v0_3/model/AbstractTest.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/AbstractTestSupport.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestAudio.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestOembed.java, src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestStorySummary.java
The StorySummary is the first model object in this artifact that isn't
directly mapped to a JSON schema, so the existing patterns I had in our
AbstractTests were a little hard to re-use without a refactor of truly
generic stuff up to the AbstractTestSupport class, which I did.
=> Adding a StorySummary object; refactoring AbstractTests to be more reusable

src/main/java/com/washingtonpost/arc/ans/v0_3/model/StoryOperation.java, src/main/resources/schema/ans/v0_3/story-operation.json
This is needed so that we can push "deletes" into Kafka and then into ElasticSearch
=> Adds "Story Operation" for non-RESTful environments

src/main/resources/schema/ans/v0_4/collection.json
This should be the top level for a collection of stores.  This makes it
clear that the top level object is not a story and in content_elements are stories.
=> Added a collection.json

tests/fixtures/story-fixture-tiny-house.json
The story-fixture-tiny-house.json example validates.  But there is a
credits element inside an image content_element.  It should match the
format of all other credit elements.  But since only id, type, channel
are defined for content_elements it validates.
=> Make content_element image credits match trait-credits.json

src/main/resources/schema/ans/0.5.3/image_operation.json
I tried to make this match existing operation schemas, but note `_id` for the ID of the image itself.
=> Schema for image_operations

lib/upvert/0.5.5.js, tests/fixtures/transforms/0.5.5/story-fixture-taxonomy-bugs.json, tests/transform-tests.js
Skips reference objects in sites array; 
Promotes additional_properties.primary to .primary when present in sites
=> Changes 0.5.5->0.5.6 upverter to 

README.md, lib/upvert/0.5.6.js, src/main/resources/schema/ans/0.5.7/gallery.json, src/main/resources/schema/ans/0.5.7/image.json, src/main/resources/schema/ans/0.5.7/image_operation.json, src/main/resources/schema/ans/0.5.7/story.json, src/main/resources/schema/ans/0.5.7/utils/content_element.json, src/main/resources/schema/ans/0.5.7/utils/reference.json, src/main/resources/schema/ans/0.5.7/video.json, tests/fixtures/schema/0.5.7/gallery-fixture-good.json, tests/fixtures/schema/0.5.7/image-fixture-good.json, tests/fixtures/schema/0.5.7/image-operation-create.json, tests/fixtures/schema/0.5.7/image-operation-update.json, tests/fixtures/schema/0.5.7/story-fixture-good.json, tests/fixtures/schema/0.5.7/video-fixture-good.json, tests/fixtures/transforms/0.5.6/story-fixture-references-with-channel.json, tests/transform-tests.js
These five commits:
1. Add a `licensable` flag to images from Anglerfish
2. Add the `channels` trait to top-level stories, videos, images, and galleries
3. Standardizes on `channels` (vs `channel` in some elements)
Tests to suit.
=> Licensable flag for images; channels

package.json, src/main/resources/schema/ans/0.5.8/utils/reference.json, tests/fixtures/schema/0.5.8/story-fixture-good.json
`alignment` should be allowed on references
Not sure this is ever actually needed in practice (would make more sense on `referent_properties` in most real world cases?) but included here for completeness
=> Reference alignment

src/main/resources/schema/ans/0.5.8/clavis_operation.json, src/main/resources/schema/ans/0.5.8/traits/trait_taxonomy.json, src/main/resources/schema/ans/0.5.8/utils/named_entity.json, tests/fixtures/schema/0.5.8/named-entity-fixture-bad-missing-id.json, tests/fixtures/schema/0.5.8/named-entity-fixture-good.json, tests/fixtures/schema/0.5.8/story-fixture-good.json, tests/schema-tests-05.js
This PR resolves #121 and adds the Named Entity type based on discussion in that Proposal. The new Named Entity type lives in `utils/` like topics and keywords. It appears in the `taxonomy` trait and the `clavis_operation` schema. 
It also adds associated tests that verify the structure of the Named Entity as well as its inclusion to the taxonomy trait.
=> Add Named Entity type

src/main/resources/schema/ans/0.5.8/traits/trait_comments.json, src/main/resources/schema/ans/0.5.8/traits/trait_source.json, src/main/resources/schema/ans/0.5.8/utils/tag.json, tests/schema-tests-05.js
(fully backwards compatible with 0.5.7)
=> Make comments, source, and tag objects open-ended 

RELEASE_NOTES.md, package.json, src/main/resources/schema/ans/0.5.8/traits/trait_publishing.json, src/main/resources/schema/ans/0.5.9/traits/trait_publishing.json, tests/fixtures/schema/0.5.8/story-fixture-tiny-house.json, tests/fixtures/schema/0.5.9/story-fixture-tiny-house.json, tests/schema-tests-05.js
As I started working on the equivalent ES index updates for trait_publishing, I realized that in 1.5 (which is the current ES version deployed for most clients) the schema we had agreed upon earlier was going to have some field collisions in certain queries that would be Not Good.  This PR largely ditches the attempts to make trait_publishing fields match the story_operation (Content Ops) type and the edition type used internally in Story API and goes for prefixed fields names instead, also adding additional_properties to both objects. 
The goal here was make sure that the queries WebSked will need will work, and also that existing queries that rely on the "published: true" query that works in 1.5 and nowhere else will not suddenly start returning false positives. 
This is somewhat bad …
=> Reworks trait_publishing to make elasticsearch 1.5 happy

src/main/resources/schema/ans/0.5.9/traits/trait_credits.json
Move "by" and "photos_by" out of the shadow schema
Slightly restrict the name conventions of "other" relationships
=> Tighten up credits object, make explicit identifiers

docs/proposals/2017-09-25_Author.md
An attempt to formalize the new transparency fields (and other author service data) in ANS in a consistent way.
=> ANS Author Proposal

lib/transforms.js, lib/upvert/0.5.8.js, src/main/resources/schema/ans/0.5.9/utils/author.json, tests/fixtures/schema/0.5.9/audio-fixture-good-streams.json, tests/fixtures/schema/0.5.9/audio-fixture-good.json, tests/fixtures/schema/0.5.9/author-fixture-good.json, tests/fixtures/schema/0.5.9/image-fixture-good.json, tests/fixtures/schema/0.5.9/image-operation-create.json, tests/fixtures/schema/0.5.9/image-operation-update.json, tests/fixtures/schema/0.5.9/reference-fixture-bad-addl-props.json, tests/fixtures/schema/0.5.9/reference-fixture-bad-more-addl-props.json, tests/fixtures/schema/0.5.9/story-fixture-bad-corrections.json, tests/fixtures/schema/0.5.9/story-fixture-bad-extra-properties.json, tests/fixtures/schema/0.5.9/story-fixture-bad-wrong-type.json, tests/fixtures/schema/0.5.9/story-fixture-bad-wrong-version.json, tests/fixtures/schema/0.5.9/story-fixture-good-mystery-element.json, tests/fixtures/schema/0.5.9/story-fixture-good.json, tests/fixtures/schema/0.5.9/story-fixture-references.json, tests/fixtures/schema/0.5.9/story-fixture-tiny-house.json, tests/fixtures/schema/0.5.9/video-fixture-good-attached-redirect.json, tests/fixtures/schema/0.5.9/video-fixture-good.json, tests/fixtures/transforms/0.5.8/author-fixture.json, tests/schema-tests-05.js, tests/transform-tests.js, tests/validator.js
This is prep work for the future, and has no immediate impact on anyone until all services support ANS 0.5.9.
- Matches author fields to Google Transparency project (new Author Service fields)
- Makes `byline` distinct from `name` and is a required field
- Makes `version` required for authors
=> Implementation of new Author object for ANS 0.5.9

src/main/resources/schema/ans/0.5.8/traits/trait_source.json
Filing this, as WebSked is expecting case sensitive "staff" and "wires" values for its filtering. "Staff" and "Wires" will not work.
=> Updated source.source_type with lowercase "staff" and "wires" examples

RELEASE_NOTES.md, src/main/resources/schema/ans/0.5.9/story_elements/endorsement.json, tests/fixtures/schema/0.5.9/endorsement-fixture-bad-missing-prop.json, tests/fixtures/schema/0.5.9/endorsement-fixture-bad-type-mismatch.json, tests/fixtures/schema/0.5.9/endorsement-fixture-good.json, tests/fixtures/schema/0.5.9/story-fixture-good.json, tests/schema-tests-05.js
Adds a new 'endorsement' element to the ANS schema.
Unit tests were added for the new schema, and a test that validates an entire story was modified to include the new element. The modified test still passes with the new element added. 
Need to update elasticsearch mappings here: 
https://github.com/WPMedia/arc-content-api-tasks/tree/development/app/services/elasticsearch_mappings
Also need to apply those updates to each ECS cluster.
None that I know of. 
n/a
Repo itself is documentation for ANS schema.
Yes
=> Implements endorsement element in ANS schema CA-318

src/main/resources/schema/ans/0.7.1/utils/named_entity.json, tests/fixtures/schema/0.7.1/named-entity-fixture-good-missing-score.json, tests/fixtures/schema/0.7.1/story-fixture-good.json, tests/schema-tests-07.js
This as an optional `score` field to the Named Entities in that `taxonomy` section of a story. The scores represent the relevancy of the Named Entity to that story. Without scores, it's impossible to determine if a story is more about one Named Entity over another.
This PR also adds associated tests surrounding the `score` field.
=> Add scores to Named Entities

docs/proposals/2018-11-13-Raw-HTML-PromoItem.md
Tronc wants to set an arbitrary raw HTML as a promo item. This should include `basic` key in the `promo_items` object. Currently, only [reference](https://github.com/washingtonpost/ans-schema/blob/master/src/main/resources/schema/ans/0.7.1/utils/reference.json) and [content](https://github.com/washingtonpost/ans-schema/blob/master/src/main/resources/schema/ans/0.7.1/content.json) types are allowed under `promo_items`.
Add [raw_html](https://github.com/washingtonpost/ans-schema/blob/master/src/main/resources/schema/ans/0.7.1/story_elements/raw_html.json) as a supported type to the both `basic` and all other keys under `promo_items` object.
```
{
"$schema": "http://json-schema.org/draft-04/schema#",
"id": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/ …
```
=> Adding raw_html type into promo_items proposal

src/main/resources/schema/ans/0.8.1/traits/trait_subtype.json
In the Arc platform, `subtype` is reserved for client definition and use. This PR updates the ANS trait and description to reflect this fact.
=> Update `subtype` trait to accurately reflect usage

lib/validator.js
Running the script to create ANS version 0.9.0 did not update the validator.js file. Manually adding it here.
=> Fixes lib/validator.js to add version 0.9.0

docs/proposals/2019-04-02_Custom_Embeds.md
Organizations have third-party content that exists outside of the Arc system that they want to include in stories. This content could be content types that Arc doesn’t support or plan to support. For example, quizzes from third-party interactives builders or story cards that are created by the organization and managed themselves. Sometimes this content may be Arc-supported content types too. Customers can choose to use another video platform provider alongside other Arc tools. Some customers such as in Europe have advanced rights management needs that the Arc platform doesn’t currently support. 
Our customers want to (a) insert this third-party content in a way that is friendly to downstream systems and (b) streamline the workflow so users could search and insert these embeds without …
=> Custom Embed proposal

src/main/resources/schema/ans/0.10.2/utils/tag.json, tests/fixtures/schema/0.10.2/story-fixture-good-taxonomy.json, tests/fixtures/schema/0.10.2/tag-fixture-bad-no-text.json, tests/fixtures/schema/0.10.2/tag-fixture-bad-subtype.json, tests/fixtures/schema/0.10.2/tag-fixture-bad-type.json, tests/fixtures/schema/0.10.2/tag-fixture-good.json, tests/schema-tests-010.js
Implements schema changes to support tag types and subtypes
* `subtype` added per proposal
* `type` added (since subtype makes little sense without it)
* Both are optional, to preserve backwards-compatibility
* tests
=> Implements schema changes to support tag types and subtypes

docs/proposals/2020-07-27-Document_Contributors.md
Proposal for adding a Document Contributors (`contributors`) field to each document type in order to track who created (and in the future, contributed at all) to a document in Arc.
=> Proposal for Document Contributors field

src/main/resources/schema/ans/0.10.9/author_operation.json, src/main/resources/schema/ans/0.10.9/site_operation.json, src/main/resources/schema/ans/0.10.9/story_elements/custom_embed.json, src/main/resources/schema/ans/0.10.9/traits/trait_id.json, src/main/resources/schema/ans/0.10.9/video_operation.json
The ANS Schema violates parts of the draft04 specification which makes it unparsable by many JSON Schema parsers.  This change is directly related to the Publishing Platform Team's work on generating application models from the ANS JSON Schema, see [this PR](https://github.com/WPMedia/arcpub/pull/1062) for more context.  The changes in this PR are backwards compatible and the updates to the tests in this PR prove it.
=> 0.10.9 Release

src/main/resources/schema/ans/0.10.9/image.json, src/main/resources/schema/ans/0.10.9/traits/trait_auth.json, src/main/resources/schema/ans/0.10.9/traits/trait_seo_filename.json, tests/fixtures/schema/0.10.9/image-fixture-bad-auth-format.json, tests/schema-tests-010.js
This PR implements the Auth & SEO Filename fields proposed by https://github.com/washingtonpost/ans-schema/pull/258.
=> Add Auth & SEO Filename traits to image ANS

src/main/resources/schema/ans/0.10.9/content_operation.json
https://arcpublishing.atlassian.net/browse/PSTK-2919
- trigger type `variant`  needs to be added for supporting new events which are triggered from denormalizer to downstream
- these new variant triggered story events are to communicate that the story content has been changed for cache busting and partner producers.
[PSTK-2919]: https://arcpublishing.atlassian.net/browse/PSTK-2919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PSTK-2919: added trigger type

RELEASE_NOTES.md, lib/schemas.js, package-lock.json, package.json
These changes: 
* Prevent the callback function from being called twice during the loading of schemas
* Prevent the load schema function from returning before the full schema is read
=> ACMS-000: release fix for schema loading function
