- pom.xml
This commit should let us distribute this ANS artifact into artifactory
and re-use it in other projects
> Descending from wp-parent-pom and adding SCM block

- README.md
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/ANS.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Collection.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Gallery.java
- src/test/java/com/washingtonpost/arc/ans/v0_2/model/TestStory.java
- src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestStory.java
- src/test/java/com/washingtonpost/legacy/README.md
These are called Story and Gallery, which are entirely the same except for presentational differences.
> Renaming Story to Collection, and then adding new subtypes of collection.

- src/main/java/com/washingtonpost/arc/ans/v0_3/model/ANS.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Oembed.java
- src/main/resources/schema/ans/v0_3/oembed.json
- src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestOembed.java
- src/test/resources/com/washingtonpost/arc/ans/v0_3/model/oembed-fixture-bad.json
- src/test/resources/com/washingtonpost/arc/ans/v0_3/model/oembed-fixture-good.json
Very basic, does what it says.
> Adds oembed

- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Collection.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Content.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/ContentElement.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/ContentListElement.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Gallery.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/RawHTML.java
- src/main/resources/schema/ans/v0_3/content_element.json
- src/main/resources/schema/ans/v0_3/trait_channel.json
- src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestText.java
- src/test/resources/com/washingtonpost/arc/ans/v0_3/model/story-fixture-good.json
- src/test/resources/com/washingtonpost/arc/ans/v0_3/model/text-fixture-good-channels.json
Adds "channel" trait in JSON Schema and makes all possible content elements descend from ContentElement in Java model
> Adds "channel" trait

- .gitignore
It'd be great to have a .gitignore file in this project to make it easier to work with!
> Add a .gitignore file!

- src/main/java/com/washingtonpost/arc/ans/v0_3/model/ANS.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Code.java
- src/main/resources/schema/ans/v0_3/code.json
- src/main/resources/schema/ans/v0_3/content_element.json
- src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestCode.java
- src/test/resources/com/washingtonpost/arc/ans/v0_3/model/code-fixture-good.json
Adds Code Sample as ANS Element (needed for dev blog)
> Adds Code Sample as ANS Element

- src/main/java/com/washingtonpost/arc/ans/v0_3/model/ANS.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/StorySummary.java
- src/main/java/com/washingtonpost/arc/ans/v0_3/model/Table.java
- src/main/resources/schema/ans/v0_3/content_element.json
- src/main/resources/schema/ans/v0_3/story-summary.json
- src/main/resources/schema/ans/v0_3/table.json
- src/main/resources/schema/ans/v0_3/text.json
- src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestStorySummary.java
- src/test/java/com/washingtonpost/arc/ans/v0_3/model/TestTable.java
- src/test/resources/com/washingtonpost/arc/ans/v0_3/model/table-fixture-good.json
- Fixes bug with StorySummary caused by very long delayed acceptance of @willvanwazer 's PR
- Makes "text" a required field on text elements
- Adds data-table element to ANS 0.3 per discussion with Eric
> Adds data-table element to ANS 0.3 per discussion with Eric

- src/main/resources/schema/ans/v0_4/section.json
- src/main/resources/schema/ans/v0_4/tag.json
- src/main/resources/schema/ans/v0_4/trait-id.json
- src/main/resources/schema/ans/v0_4/trait-taxonomy.json
> Taxonomy refactor

- src/main/resources/schema/ans/v0_4/content.json
- src/main/resources/schema/ans/v0_4/trait-copyright.json
- src/main/resources/schema/ans/v0_4/trait-credit.json
- tests/fixtures/audio-fixture-good.json
- tests/fixtures/video-fixture-good.json
- tests/fixtures/video-fixture-nationals.json
- tests/schema-tests.js
- Fixes bug in content.json where all references were not being included
- Removed "required" from credit
> Fixes bug in content.json where all references were not being included

- tests/fixtures/transforms/0.5.3/story-fixture-good-mystery-element.json
- tests/fixtures/transforms/0.5.3/story-fixture-good.json
- tests/fixtures/transforms/0.5.5/image-fixture-good-no-height-width.json
- tests/fixtures/transforms/0.5.5/image-fixture-good.json
- tests/fixtures/transforms/0.5.5/story-fixture-good-mystery-element.json
- tests/fixtures/transforms/0.5.5/story-fixture-good-planning.json
- tests/fixtures/transforms/0.5.5/story-fixture-good-references-2.json
- tests/fixtures/transforms/0.5.5/story-fixture-good-references-3.json
- tests/fixtures/transforms/0.5.5/story-fixture-good-slugs.json
- tests/fixtures/transforms/0.5.5/story-fixture-good.json
- tests/fixtures/transforms/0.5.5/story-fixture-misspelled-additional-properties.json
- tests/fixtures/transforms/0.5.5/story-fixture-promo-items-empty.json
- tests/fixtures/transforms/0.5.5/story-fixture-promo-items-no-basic.json
- tests/fixtures/transforms/0.5.5/story-fixture-references.json
- tests/fixtures/transforms/0.5.5/story-fixture-taxonomy-bugs.json
- tests/fixtures/transforms/0.5.5/story-fixture-tiny-house.json
- tests/fixtures/transforms/0.5.5/story-fixture-versions.json
- tests/fixtures/transforms/0.5.5/video-fixture-good.json
- tests/fixtures/transforms/0.5.5/video-fixture-nationals.json
- tests/transform-tests-05.js
Fixes transform test to validate each step after transforming,
Adds 0.5.5 fixtures for transforms
Fixes 0.5.3 fixtures for transforms
> Upverter test fixes

- LICENSE
This corrects a typographical error in the license.
> Update the year and stakeholders in the LICENSE file

- src/main/resources/schema/ans/0.5.8/audio.json
- src/main/resources/schema/ans/0.5.8/content.json
- src/main/resources/schema/ans/0.5.8/gallery.json
- src/main/resources/schema/ans/0.5.8/image.json
- src/main/resources/schema/ans/0.5.8/results.json
- src/main/resources/schema/ans/0.5.8/story.json
- src/main/resources/schema/ans/0.5.8/story_elements/blockquote.json
- src/main/resources/schema/ans/0.5.8/story_elements/code.json
- src/main/resources/schema/ans/0.5.8/story_elements/element_group.json
- src/main/resources/schema/ans/0.5.8/story_elements/header.json
- src/main/resources/schema/ans/0.5.8/story_elements/interstitial_link.json
- src/main/resources/schema/ans/0.5.8/story_elements/raw_html.json
- src/main/resources/schema/ans/0.5.8/story_elements/table.json
- src/main/resources/schema/ans/0.5.8/story_elements/text.json
- src/main/resources/schema/ans/0.5.8/traits/trait_alignment.json
- src/main/resources/schema/ans/0.5.8/utils/content_element.json
- src/main/resources/schema/ans/0.5.8/video.json
- tests/fixtures/schema/0.5.8/element-group-fixture-good.json
- tests/fixtures/schema/0.5.8/image-fixture-bad-alignment.json
- tests/fixtures/schema/0.5.8/story-fixture-good.json
- tests/fixtures/schema/0.5.8/story-fixture-tiny-house.json
- tests/schema-tests-05.js
https://github.com/washingtonpost/ans-schema/issues/84
https://github.com/washingtonpost/ans-schema/issues/85
> Adds element_group element, alignment property

- lib/transform_utils.js
- lib/upvert/0.5.7.js
- package.json
- src/main/resources/schema/ans/0.5.8/traits/trait_label.json
- src/main/resources/schema/ans/0.5.8/traits/trait_source.json
- tests/fixtures/schema/0.5.8/label-bad-arbitrary-properties.json
- tests/fixtures/schema/0.5.8/label-bad-field-name-with-dots.json
- tests/fixtures/schema/0.5.8/label-good.json
- tests/fixtures/schema/0.5.8/source-bad-extra-properties.json
- tests/fixtures/schema/0.5.8/source-good.json
- tests/fixtures/schema/0.5.8/story-fixture-good.json
- tests/fixtures/transforms/0.5.7/story-fixture-good-old-labels-recursive.json
- tests/fixtures/transforms/0.5.7/story-fixture-good-old-style-label-and-source.json
- tests/fixtures/transforms/0.5.7/story-fixture-good.json
- tests/schema-tests-05.js
- tests/transform-tests.js
> Formalizes schema for label, source; adds upverter

- lib/upvert/0.5.7.js
- package.json
- src/main/resources/schema/ans/0.5.8/traits/trait_comments.json
- tests/fixtures/schema/0.5.8/story-fixture-good.json
- tests/fixtures/transforms/0.5.7/story-fixture-good.json
- tests/transform-tests.js
> 92 comments

- package.json
- src/main/resources/schema/ans/0.5.8/video.json
- tests/fixtures/schema/0.5.8/video-fixture-good.json
Fixes #99 
Per request, reduced this to just an `embed_html` field
> Adds embed_html to video object

- RELEASE_NOTES.md
- lib/upvert/0.5.7.js
- lib/validator.js
- src/main/resources/schema/ans/0.5.8/utils/table_cell.json
- src/main/resources/schema/ans/0.5.8/utils/table_row.json
- tests/fixtures/schema/0.5.8/story-fixture-tiny-house.json
- tests/fixtures/schema/0.5.8/table-fixture-bad.json
- tests/fixtures/schema/0.5.8/table-fixture-good.json
- tests/fixtures/transforms/0.5.7/story-fixture-tiny-house.json
- tests/validator.js
Redo of table format for ANS 0.5.8, with changes to upverter and validator
Fixes #104
> Content elements tables

- lib/upvert/0.5.7.js
- package.json
- src/main/resources/schema/ans/0.5.8/planning_note_operation.json
- src/main/resources/schema/ans/0.5.8/platform_pitch_operation.json
- src/main/resources/schema/ans/0.5.8/publication_pitch_operation.json
- src/main/resources/schema/ans/0.5.8/traits/trait_related_content.json
- tests/fixtures/schema/0.5.8/story-fixture-good.json
- tests/fixtures/schema/0.5.8/trait-related-content-bad-attached-redirect-has-multiple-items.json
- tests/fixtures/schema/0.5.8/trait-related-content-bad-attached-redirect-is-not-redirect.json
- tests/fixtures/schema/0.5.8/video-fixture-good-attached-redirect.json
- tests/fixtures/transforms/0.5.7/video-fixture-good-related-content-redirect.json
- tests/schema-tests-05.js
- tests/transform-tests.js
> Make related_content.redirect a reserved slot for a redirect object.

- src/main/resources/schema/ans/0.5.8/video.json
- tests/fixtures/schema/0.5.8/video-fixture-good.json
> Adds corrections to video

- src/main/resources/schema/ans/0.5.9/gallery.json
- src/main/resources/schema/ans/0.5.9/story.json
* Remove duplicate `channels` from `gallery`,
* Move `content_restrictions` in `gallery` down where it belongs,
* Move `corrections` in `story` down where it belongs.
> Remove duplicate property and order properties to match super

- docs/proposals/2017-05-10 - Audio Transcription.md
A transcription settings + results field for Arc Voice (or other projects)
> Adds first pass at audio transcription template

- src/main/resources/schema/ans/0.5.8/utils/reference.json
- src/main/resources/schema/ans/0.5.9/utils/reference.json
- tests/fixtures/schema/0.5.8/reference-fixture-bad-array.json
- tests/fixtures/schema/0.5.9/reference-fixture-bad-array.json
- tests/schema-tests-05.js
> Fixes bug where unvalidated arrays are allowed in any position where

- RELEASE_NOTES.md
- package.json
- src/main/resources/schema/ans/0.5.9/story_elements/rating.json
- tests/fixtures/schema/0.5.9/rating-fixture-bad.json
- tests/fixtures/schema/0.5.9/rating-fixture-good-only-rating.json
- tests/fixtures/schema/0.5.9/rating-fixture-good.json
- tests/fixtures/schema/0.5.9/story-fixture-good.json
- tests/schema-tests-05.js
Adds a new 'rating' element to the ANS schema.
Unit tests were added for the new schema, and a test that validates an entire story was modified to include the new element. The modified test still passes with the new element added. 
Deploying changes to ANS can be tricky, will have to come up with plan for deployment.
(Any obvious side effects that I am missing?)
None that I know of. 
n/a
Repo itself is documentation for ANS schema.
Yes
> Adds rating element to ANS schema CA-317

- src/main/resources/schema/ans/0.5.9/story_elements/numeric_rating.json
- tests/fixtures/schema/0.5.9/numeric-rating-fixture-bad.json
- tests/fixtures/schema/0.5.9/numeric-rating-fixture-good-only-rating.json
- tests/fixtures/schema/0.5.9/numeric-rating-fixture-good.json
- tests/fixtures/schema/0.5.9/rating-fixture-good-only-rating.json
- tests/fixtures/schema/0.5.9/story-fixture-good.json
- tests/schema-tests-05.js
> Changes name of new element in ANS schema from rating to numeric_rating CA-317

- docs/proposals/2018-01-08_-_MultiSite.md
- lib/transforms.js
- lib/validator.js
- package.json
- src/main/resources/schema/ans/0.6.0/gallery.json
- src/main/resources/schema/ans/0.6.0/story.json
- src/main/resources/schema/ans/0.6.0/traits/trait_canonical_url.json
- src/main/resources/schema/ans/0.6.0/traits/trait_canonical_website.json
- src/main/resources/schema/ans/0.6.0/traits/trait_taxonomy.json
- src/main/resources/schema/ans/0.6.0/traits/trait_website.json
- src/main/resources/schema/ans/0.6.0/traits/trait_website_url.json
- src/main/resources/schema/ans/0.6.0/traits/trait_websites.json
- src/main/resources/schema/ans/0.6.0/utils/reference.json
- src/main/resources/schema/ans/0.6.0/utils/section.json
- src/main/resources/schema/ans/0.6.0/video.json
- tests/fixtures/schema/0.6.0/story-fixture-good-multi-site.json
- tests/schema-tests-06.js
Adds proposal and basic implementation of multi-site schema
> Multisite 0.6.0

- docs/proposals/2018-02-06_Line_Count_Planning.md
This PR is for a simple change that will ensure consistency in how story length data are ingested and processed by WebSked.
> Proposal: Line Count Planning

- docs/proposals/2018-02-21-Distributor.md
Adds proposal for distributor fields and owner field re-alignment
> Distributor fields

- src/main/resources/schema/ans/0.6.1/audio.json
- src/main/resources/schema/ans/0.6.1/content.json
- src/main/resources/schema/ans/0.6.1/gallery.json
- src/main/resources/schema/ans/0.6.1/image.json
- src/main/resources/schema/ans/0.6.1/story.json
- src/main/resources/schema/ans/0.6.1/traits/trait_copyright.json
- src/main/resources/schema/ans/0.6.1/traits/trait_distributor.json
- src/main/resources/schema/ans/0.6.1/traits/trait_owner.json
- src/main/resources/schema/ans/0.6.1/traits/trait_source.json
- src/main/resources/schema/ans/0.6.1/video.json
- tests/fixtures/schema/0.6.1/story-fixture-good.json
https://github.com/washingtonpost/ans-schema/blob/master/docs/proposals/2018-02-21-Distributor.md
Adds implementation of distributor fields, deprecation notices for owner.name, source.name, source.source_type
> Implements proposal #161

- docs/proposals/2018-10-16 - Referenced Distributor.md
https://arcpublishing.atlassian.net/secure/RapidBoard.jspa?rapidView=108&projectKey=CA&modal=detail&selectedIssue=CA-1048
This is to add referencing distributors by id as an option.
> CA-1048: referenced distributor proposal

- src/main/resources/schema/ans/0.8.1/audio.json
- src/main/resources/schema/ans/0.8.1/collection.json
- src/main/resources/schema/ans/0.8.1/content.json
- src/main/resources/schema/ans/0.8.1/gallery.json
- src/main/resources/schema/ans/0.8.1/image.json
- src/main/resources/schema/ans/0.8.1/story.json
- src/main/resources/schema/ans/0.8.1/traits/trait_vanity_credits.json
- src/main/resources/schema/ans/0.8.1/video.json
- tests/fixtures/schema/0.8.1/story-fixture-tiny-house.json
> Implementation of #178

- src/main/resources/schema/ans/0.8.1/image.json
- src/main/resources/schema/ans/0.8.1/traits/trait_alt_text.json
- tests/fixtures/schema/0.8.1/image-fixture-good.json
Alt Text implementation of proposal from PR #189
> AN-1846: implementation of Alt Text proposal

- README.md
Added some instructions on how to create a new ANS version.
> CA-1407 Updates readme with version creation instructions

- docs/proposals/2019-02-08 - Recommended View.md
Proposal for a new field to indicate optimal rendering method
> Proposal recommended view

- docs/proposals/2019-02-14_Dropcap.md
This is the initial proposal for adding `dropcap`'s to ans content elements of type `text` and `header`
> EL-2613: Proposal for Dropcaps

- docs/proposals/2019-03-18-Links-List.md
A proposal for embedded and curated "See More" boxes
> Links list proposal

- src/main/resources/schema/ans/0.10.0/story_elements/interstitial_link.json
- src/main/resources/schema/ans/0.10.0/story_elements/link_list.json
- tests/fixtures/schema/0.10.0/interstitial-link-fixture-good-2.json
- tests/fixtures/schema/0.10.0/link-list-fixture-bad.json
- tests/fixtures/schema/0.10.0/link-list-fixture-good.json
- tests/fixtures/schema/0.10.0/story-fixture-tiny-house.json
- tests/schema-tests-010.js
> Implementation of link_list element

- docs/proposals/2019-07-12_Image_Focal_Point_Proposal.md
This PR includes the proposal for adding focal point to ANS for use in images.
> Focal Point Proposal

- src/main/resources/schema/ans/0.10.3/story.json
- src/main/resources/schema/ans/0.10.3/traits/trait_rendering_guides.json
Implemented the [Recommended View](https://github.com/washingtonpost/ans-schema/blob/master/docs/proposals/2019-02-08%20-%20Recommended%20View.md) proposal
> Added rendering_guides trait to a story with a preferred_method field

- docs/proposals/2019-10-22-Geo-Restriction-Ids.md
Ticket: https://arcpublishing.atlassian.net/browse/CA-1911
A proposal for adding geo-restriction ids to the `content_restrictions` trait.
> Geo Restrictions Association Proposal: CA-1911

- docs/proposals/2019-10-22_Linkless_Link_Lists.md
https://arcpublishing.atlassian.net/browse/COMP-3465
> Proposal for Text Only Elements in Link Lists

- docs/proposals/2019-09-30 - Content by reference in Link Lists.md
COMP-3310 - ANS proposal: content by reference in Link Lists
https://arcpublishing.atlassian.net/browse/COMP-3310
This PR includes a proposal for adding `story`, `video`, and `gallery` to interstitial link. An implementation PR will follow upon approval of this proposal.
> Content by reference in Link Lists Proposal

- src/main/resources/schema/ans/0.10.4/story_elements/link_list.json
- src/main/resources/schema/ans/0.10.4/traits/trait_content_restrictions.json
- tests/fixtures/schema/0.10.4/geo-restriction-fixture-bad-length.json
- tests/fixtures/schema/0.10.4/geo-restrictions-fixture-bad-empty.json
- tests/fixtures/schema/0.10.4/geo-restrictions-fixture-bad-property.json
- tests/fixtures/schema/0.10.4/geo-restrictions-fixture-bad-type.json
- tests/fixtures/schema/0.10.4/geo-restrictions-fixture-good.json
- tests/fixtures/schema/0.10.4/link-list-fixture-good-all-text.json
- tests/fixtures/schema/0.10.4/link-list-fixture-good-text.json
- tests/fixtures/schema/0.10.4/video-fixture-bad-empty-geo-restriction.json
- tests/schema-tests-010.js
Implements the geo-restriction proposal: https://github.com/washingtonpost/ans-schema/blob/master/docs/proposals/2019-10-22-Geo-Restriction-Ids.md
and
Implements the linkless link list proposal: https://github.com/washingtonpost/ans-schema/blob/master/docs/proposals/2019-10-22_Linkless_Link_Lists.md
> Implements geo-restriction and linkless link list proposals: CA-1917

- docs/proposals/2020-02-20-Planned_Actual_Char_Count.md
- src/main/resources/schema/ans/0.10.5/traits/trait_planning.json
- tests/fixtures/schema/0.10.5/trait-planning-fixture-good.json
Implements proposal https://github.com/washingtonpost/ans-schema/pull/227
> Adding character count data to story planning trait

- src/main/resources/schema/ans/0.10.5/collection.json
- src/main/resources/schema/ans/0.10.5/traits/traid_dynamic_items.json
- src/main/resources/schema/ans/0.10.5/traits/trait_dynamic_items.json
- tests/fixtures/schema/0.10.5/collection-fixture-good.json
Implementation of [query backfill proposal](https://github.com/washingtonpost/ans-schema/pull/231)
> PSTK-1362 - Query Backfill

- RELEASE_NOTES.md
- lib/schemas.js
- package.json
added return after callback to avoid code execution if there is an error or if it is finished
> PPSE-1454: added return after callback to avoid code execution if there is an error or if it is finished

- docs/proposals/2022-06-31 - Conditional Content.md
* Initial commit of documentation for using conditional content in ANS version 0.10.9 or later
> PSTK-2743: Documentation for Conditional Content

- src/main/resources/schema/ans/0.10.9/traits/trait_variations.json
PSTK-2799: As a spoke author,
I can create content for my variant
https://arcpublishing.atlassian.net/browse/PSTK-2799
> Fix a missed file rename.

- src/main/resources/schema/ans/0.10.9/utils/variant.json
PSTK-2799: As a spoke author,
I can create content for my variant
https://arcpublishing.atlassian.net/browse/PSTK-2799
> Correct "websites" "maxItems" specification.

- RELEASE_NOTES.md
- package-lock.json
- package.json
PSTK-2799: As a spoke author,
I can create content for my variant
https://arcpublishing.atlassian.net/browse/PSTK-2799
> Pre-release version containing schema changes for Conditional Content
